### ISSUE TITLE
Generate Spreadsheet fails for some Studies

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#256]
Instance:    EFD_HM
User:           OIHM

Can generate the spreadsheet for the following studies:

- A Study
- Test FoodStocks

Fails for all others:

> Template failed to be created - Null

Including a copy of a study i can generate the spreadsheet for.
For example, "generate copy of generatable study" is a copy of "A Study`"

**Comment by dbrownukk** [comment]
FoodStocks not copied over in copyStudy caused this. 

Fixed - to be deployed

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
I assume the already corrupted projects that failed before should still fail.
Copies of them also still fail.
Copies of projects that worked before work now so this appears to be fixed,
Andi created a new study added a food stock item and copied of it. 
They both generate.

So i'm going to close this as fixed.
