### ISSUE TITLE
Units Other Use column should precede Units Consumed column, which should be calculated automatically

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#293]
This is a usability issue that exists in OHEA as well see (issue #172 )

Normal best practice is to specify Units Produced, Units Sold, Units Other Use (e.g. gift or whatever) and then whatever remains is Units Consumed.
To avoid errors in data collection, it would be preferable if the Units Consumed column is calculated:-
Units Consumed = Units Produced - Units Sold - Units Other Use.

This occurs in Crops, Livestock Products & Wild Foods tabs

**Comment by dbrownukk** [comment]
Fixed the order of columns in spreadsheet generation 

Units Consumed is calculated on insert/update of Crop/LSP and WF within database and on parse of spreadsheet.

Could we remove Units Consumed from spreadsheet completely?

**Comment by daiClegg** [comment]
Is this deployed?
I tried to test & the Spreadsheet version still shows V1 & the column order is as was/

**Comment by daiClegg** [comment]
Re your question:

>Could we remove Units Consumed from spreadsheet completely?

I think it's there because the spreadsheet might not make the calculation automatically. 
Since OIHM/OHEA can calculate it anyway, i think there is a case for dropping it.
However i am more inclined to allow the user to enter it, and then ignore it on upload.
Because 
- we get accurate data.
- we don't have to confuse or re-train anyone who expects that fiied to be there. 
- over time, manual practice will lapse anyway
- new users will know to ignore it.

It would be cleaner to remove it, but i think leaving it makes for a quieter life at no risk to data quality.

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by daiClegg** [comment]
This fix completes the requirement in #163 for OIHM,
Backporting to OHEA remains - as reflected in #163
